export const meta = {
  name: 'forge-every-aspect',
  description: 'Author 9 more house skills (castle, world, cloud, ship, qa, audio, feel, l10n, onboarding) — each mapped from code, then adversarially verified and fixed',
  phases: [
    { title: 'Author', detail: '9 authors: map the code, then write the skill draft' },
    { title: 'Verify+Fix', detail: '9 verifiers: check 25+ claims each and fix the draft' },
  ],
}

const OWNER = `The game owner asked for this directly, in their own words: "creating more high level skills regarding every aspect of this game... no cut corners, make them perfect." You are one of the agents doing it. Repo: D:/CastleConquest (Godot 4.7.2 landscape-only Android game: a LIVE persistent medieval realm — castle view <-> realm map, siege combat, economy, alliances). Windows; PowerShell 5.1 only (no &&, use ';'). Binding: D:/CastleConquest/CLAUDE.md (verify never assume; keep the painted identity; no title menus / single-player conventions; server/database budget EUR 200/month; sacred balance constants; one writer per file). Owner ledger: D:/CastleConquest/PROJECT_MASTER_MEMORY.md (read §99 CURRENT STATE, then grep your topic — issue ids like UI-004, PERF-004b, SEC-003 carry the real history), D:/CastleConquest/upgrade/TASK_BOARD.md, D:/CastleConquest/upgrade/MASTER_OVERHAUL_DIRECTIVE.md, D:/CastleConquest/tools/fleet/MASTER_TASKS.md (detailed history; read the parts about your topic).`

const HOUSE = `THE HOUSE SKILLS (read them first for structure, tone and boundaries; your skill must link to them instead of duplicating them): installed — D:/CastleConquest/.claude/skills/blender-forge/ (hero-quality 3D props/equipment, cards, baked GLB), reference-forge/ (Met CC0 + owner boards reference loop), game-art-director/ (2D painted pipeline, tools/assets.json + gen_assets.py). In progress (drafts in D:/CastleConquest/art/skills_draft/ may or may not exist yet): ui-forge (events/menus/alliance/buttons UI), story-forge (narrative), shop-forge (bundles/monetization), gameplay-forge (systems, balance, combat, progression). The NINE new skills being written right now: castle-forge, world-forge, cloud-forge, ship-forge, qa-forge, audio-forge, feel-forge, l10n-forge, onboarding-forge — each owns its domain; name the boundary where yours touches another.`

const SHAPE = `QUALITY BAR (no cut corners):
- SKILL.md: YAML frontmatter (name, and a precise 'description' that states WHAT it does and WHEN to use it with trigger phrases); HARD RULES first (each one grounded: cite file:line, constant name+value, test name, or ledger id); the workflow in order; a router table to the reference files; the harness commands that prove work in this domain.
- 5-8 reference files, each 60-160 lines, dense and actionable: exact file paths, function/constant names with values, data shapes with field names, the real numbers (sizes, budgets, timings, counts), worked examples drawn from this repo's history, and the exact commands (full Godot path: C:/Users/Famil/AppData/Local/Microsoft/WinGet/Packages/GodotEngine.GodotEngine_Microsoft.Winget.Source_8wekyb3d8bbwe/Godot_v4.7.2-stable_win64_console.exe; headless vs windowed rules from CLAUDE.md).
- references/lessons.md: ONLY real recorded traps from the ledger/history, numbered, each with its evidence id — at least 10 if the history has them.
- Never invent: if a system, test, or file does not exist, say so and give the proposal shape. Every claim must survive a verifier checking it against the code.
MAP BEFORE YOU WRITE: read the code you are documenting (not just docs about it). Record what you read.
FILE RULE: write ONLY into your staging folder D:/CastleConquest/art/skills_draft/<skill-name>/ — never into .claude/ (the lead installs; the owner authorized it). Do not edit any game file.
RETURN: the file list with line counts, the 12 most important rules as encoded, and anything you could not verify.`
const RESUME = `RESUME NOTICE (read first): your earlier run of this exact job was cut off by a usage limit on 2026-09-26. Part of your draft is ALREADY ON DISK in your staging folder. List and read what exists first, then COMPLETE it — keep what is good, fix what is wrong, write only what is missing. The owner is paying for this run: be economical, no re-reading beyond what completion needs.\n\n`

const SKILLS = [
  { name: 'castle-forge', resume: true, scope: `THE CASTLE AND TOWN — the shipped procedural building kit and the castle view. Cover: tools/blender/ (build.py families and flags, generators/buildings.py ARCHETYPES (34) x 6 tiers via config/tiers.py, parts.py (P.footing/P.plinth, never P.pad), primitives.py Model, config/palette.py ROLES (library.cfg raises; timber_dark is a material, role timber_aged), config/skins.py seat skins, export/glb.py finish pass Weld->Bevel->EdgeSplit + Budget reports, check_aspect.py fortress ladder KEEP_ASPECT 1.50 "Ladder holds", catalogue.py / BLENDER_CATALOGUE.md), the staging->judge->promote wave process (WAVE2_PLAN.md, art/export/wave1/, judge verdicts), godot/castle/ (castle_builder.gd, town_plan.gd = the ONE master grid, placement.gd, castle_view.gd, blender_kit.gd MODEL + tier_for), build_thumbs, the castle puzzle (W3b: move mode, footprints, SAVE_VERSION migration), wards/territory (FEAT-005 append-only plots), moat (FEAT-006), dressing (C3/C4), the harnesses (structure_audit, collision_audit, cv_keep_reconcile, placement_test, skin_contract_test, pm_render_probe). Boundary: blender-forge owns hero props; this owns the shipped low-poly kit and its contracts.` },
  { name: 'world-forge', scope: `THE REALM MAP — godot/world/world_map.gd, TerrainField (realm seed, DEPTH-001), biomes, lighting.gd + fog (the LM fog-was-inert finding), camera_rig.gd (fixed 55 deg pitch, per-aspect solve), camps / barbarian towers (tools/blender/generators/barbarians.py 6 stages; camp ladder), AI lords (routines, grudges, raid pressure held to the corridor), marches (march_out.gd, march timing, the teleport/negative-index fixes), POIs/landmarks/territory readability, map performance (terrain pan hitch PERF work 14->3 frames), world harnesses (realm_probe, map_trap_probe, fenv_b_weather_probe, pf1 probes, march_probe). Boundary: gameplay-forge owns the combat math; this owns the map, its presentation and its simulation surfaces.` },
  { name: 'cloud-forge', scope: `THE ONLINE BACKEND on a EUR 200/month budget (owner ruling 2026-09-26; the earlier design was sized for EUR 50 — see the addendum at the end of PROJECT_MASTER_MEMORY.md). Cover: godot/core/cloud.gd (push/save beats PUSH_EVERY, MIN_WRITE_GAP, print=silent, pointer-first boards, mail/chat throttles), firebase/ (database rules, README, COST_AUDIT.md, the one Cloud Function, check_rules.ps1), MULTIPLAYER_STATUS.md (the server-authority design), save envelope signing + _sanitise + tamper cases (persist/saverobust), sign-in / identity (USER-8 Play Games, guest linking, the Auth MAU cost line: free to 50k MAU then $0.0055), core/sd_cost_probe.gd and the measured bill (RTDB bills downloads + storage, not operations), anti-cheat and server-side siege design (SEC-003), backups, and the EUR 200 headroom plan (what it unlocks: server-side siege checking, per-event rankings FEAT-004, live season ladder) with the rule that every new network path must be re-costed with sd_cost_probe and budget alerts set (Blaze has no spending cap). Harnesses: cloud_test, persist_test, saverobust_test, sd_cost_probe.` },
  { name: 'ship-forge', scope: `BUILD, PERFORMANCE AND RELEASE — export presets (Android: package, targetSdk 36, 16 KB pages, gradle off, include_filter carrying the flags folder), APK/AAB size history (PERF-004/004b: 184 -> 119 MB, how each pass was measured), import pipeline traps (BUG-001 exit-255 mid-write, BUG-002 sidecar channel lock, verify by path-hashed .md5 never basename, 2-3 --import passes), texture compression / VRAM (mode-2 decision, tools/vram_sidecars.py), audio OGG re-encode, video re-encode, Play Asset Delivery, performance measurement (PERF-001..003 device items, TTI 3.6 -> 1.85 s PM-H9, pf1 probes, draw calls), the real-phone smoke gate (AB-08 emulator Vulkan black), release signing / keystore, Play Console / billing / privacy URL checklist (upgrade/GOOGLE_PLAY_CHECKLIST.md, Menus.PRIVACY_URL owner item), stray-file hygiene (~40 instruments hard-coding D:/ OUT paths, stray PNGs in godot/).` },
  { name: 'qa-forge', resume: true, scope: `TESTING AND VERIFICATION — the harness battery (godot/core/ ~440 *_test/*_audit/*_probe/*_shot; the core gate list and windowed suites in CLAUDE.md), Rule Zero (verify, never assume) and the evidence standard, how to write a new probe correctly (the recorded probe traps: autoloads not in tree during _initialize so run from _process, GDScript lambdas capture locals BY VALUE, probe_mode() suppressing ceremonies, QASandbox.arm, per-worker user://, check floors — QA-06: 16 suites passed after running zero checks, verdict lines not exit codes), headless vs windowed (windowed suites refuse headless; headless ignores --resolution), shot_diff baseline (tools/shot_diff.py, 6% tolerance, bless only intended change), the QA fuzzer agent (tools/qa/agent.py, memory.json, selftest, INBOX), ui_art_audit.py, backlog_gen (never hand-edit the backlog), the §7 final-audit gate, checkpoint folders and skeptic diffs (no git by owner choice).` },
  { name: 'audio-forge', resume: true, scope: `AUDIO — godot/audio.gd (music playlists, ambience player _ambient + AMBIENCE_DB, fades, ducking incl. RewardBurst and battle report ducks, per-mode music, set_enabled, volume settings), godot/audio/ and sfx folders (what exists, formats), AUD-001 (the synthesized bailey ambience: exact recipe), the OGG Vorbis re-encode pass (imageio_ffmpeg, q4, loop flags), the ALIAS rows (good news finally has a recording), UI sound wiring (A1 leftovers, ui_press_wood 2 dB), the low-bell re-tune, owner items (5 UI sound recordings, hold/good/fanfare.ogg), how to add a sound end to end, the probes (ambience_probe etc.).` },
  { name: 'feel-forge', scope: `MOTION, JUICE AND CEREMONIES — the motion rules (W3-motion: banned easing curves §5.1, keep ceremony 8 s -> 2 s except silhouette levels §5.3, battle-won 1800 ms skippable), UI.reduced_motion (every motion must honour it), ceremonies (keep ceremony KC-C defer-and-drain after the welcome card, chest opening 4-frame sequence, branch mastery, season close, acquisition ceremony), feedback (battle report shake on CanvasLayer offset not position — FEEL-001, completion dust CPUParticles3D FEEL-002, recruits marching out, counters that roll then land, RewardBurst), the M1 Alive pass (>= 6 simultaneous idle ambient systems) and the juice standard (variant pools x3+, one-popup law, shout-tier enemy-march cue), villager life (godot/world/people.gd gait/idle/work — measured constants, never translate the pelvis in idle), the hero stage living light (godot/ui/mm_hero_stage.gd), VFX glow rules shared with blender-forge.` },
  { name: 'l10n-forge', resume: true, scope: `LOCALIZATION — godot/ui/strings.gd (S.t / S.f keys), L10N-001 (English-only v1 decision + migration plan), upgrade/W7_I18N_PLAN.md (7 languages, three-tier string classification, probes->key matching FIRST so billing gates are never falsely green, data-table extraction build step, Noto CJK/Cyrillic fallback chain, pseudo-locale +40% layout gate, money strings per-locale legal review), where hard-coded player-facing strings still live (grep the data tables and UI), plural and number/time formatting (Items.pretty_time, the §5d human units), layout risks (the Button-min-width law UI-004, clip_text), font atlases and APK size, the test plan.` },
  { name: 'onboarding-forge', scope: `ONBOARDING AND RETENTION — the first session (boot splash -> loading -> the bailey; UX-001 no title menu; the prologue pages STORY-003; the 5-step coach with painted gauntlet/check/card/skip UI-002), second-session guidance (ONBD-001 steward counsel), welcome-back card (FEEL-001 offline estimate capped at the burner's 8000), the Meanwhile router (GAME-001 dead air), notifications/badges/herald, daily ladder and events cadence as return hooks, the W10 plan (15-minute onboarding ladder, grip teach, steward/herald mascots STW/HRD), the day-1/7/30/90 instruments, what must never happen (dead ends, fake timers, pressure tactics — the money law and PEGI-7), the harnesses (session_audit 14 checks, ux_flow_probe, ob_ceremony, feel_shot).` },
]

const results = await pipeline(
  SKILLS,
  (s) => agent(`${s.resume ? RESUME : ''}${OWNER}
${HOUSE}
YOU ARE THE AUTHOR OF: ${s.name}. Staging folder: D:/CastleConquest/art/skills_draft/${s.name}/
SCOPE: ${s.scope}
${SHAPE}`, { label: `author:${s.name}`, phase: 'Author', effort: 'max' }),
  (authored, s) => agent(`${OWNER}
YOU ARE THE ADVERSARIAL VERIFIER-FIXER for the skill draft at D:/CastleConquest/art/skills_draft/${s.name}/ (written by another agent; its summary: ${String(authored).slice(0, 2500)}).
1. Read every file in the draft.
2. Pick AT LEAST 25 checkable claims spread across all files (constant names + values, file paths, function names, test names + commands, ledger ids, numbers, rules) and VERIFY each against the repo with Grep/Read. Default to doubt.
3. FIX every WRONG or INEXACT claim directly in the draft files (staging only — never touch game files or .claude/). Remove anything invented; mark genuine proposals as PROPOSAL.
4. Check the skill as a whole: frontmatter valid; the description would trigger on the right requests; hard rules match the owner's rulings; nothing important in the scope is missing (add it if you can ground it); boundaries with the other house skills are named.
5. Write D:/CastleConquest/art/skills_draft/${s.name}/VERIFY.md: every checked claim (HOLDS / FIXED / REMOVED + file:line evidence) and the completeness fixes you made.
Scope the author was given: ${s.scope}
Return: counts HOLDS/FIXED/REMOVED, the 5 most serious fixes, and a one-line verdict (READY / NEEDS OWNER INPUT on <what>).`, { label: `verify:${s.name}`, phase: 'Verify+Fix', effort: 'max' }),
)
return SKILLS.map((s, i) => ({ skill: s.name, verdict: results[i] }))
